ENGINE_ADA = "text-embedding-ada-002"
GPT_DEFAULT = "4"
USE_GEMINI = true
GEMINI_API_KEY = "place for the Gemini API Key"
GEMINI_CHAT_MODEL = "gemini-1.5-flash"
GEMINI_EMBEDDING_MODEL = "models/text-embedding-004"